trigger:
  branches:
    include:
      - master

pr:
  paths:
    include:
      - 'frontend-app/**'

pool:
  vmImage: 'ubuntu-latest'

variables:
  pnpm_config_cache: $(Pipeline.Workspace)/.pnpm-store
  
steps:
  - task: Cache@2
    inputs:
      key: 'pnpm | "$(Agent.OS)" | frontend-app/pnpm-lock.yaml'
      path: $(pnpm_config_cache)
    displayName: Cache pnpm

  - script: |
      corepack enable
      corepack prepare pnpm@latest-8 --activate
      pnpm config set store-dir $(pnpm_config_cache)
    displayName: "Setup pnpm"

  - script: |
      cd frontend-app/
      pnpm install
      pnpm run build
    displayName: "pnpm install and build"

  - script: |
      cd frontend-app/
      pnpm run test
    displayName: "pnpm test"
    