apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  namespace: monitoring
  labels:
    app: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
        - name: jaeger
          image: jaegertracing/all-in-one:latest
          ports:
            - containerPort: 13177
            - containerPort: 16686
            - containerPort: 4317
          env:
            - name: COLLECTOR_OTLP_ENABLED
              value: "true"
            - name: LOG_LEVEL
              value: "debug"
            - name: METRICS_STORAGE_TYPE
              value: "prometheus"

---

apiVersion: v1
kind: Service
metadata:
  name: jaeger
  namespace: monitoring
spec:
  selector:
    app: jaeger
  ports:
    - name: otlp-port
      protocol: TCP
      port: 13133
      targetPort: 13177
    - name: ui-port
      protocol: TCP
      port: 16686
      targetPort: 16686
    - name: grpc-port
      protocol: TCP
      port: 4317
      targetPort: 4317
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-ext
  namespace: monitoring
spec:
  selector:
    app: jaeger
  ports:
    - name: ui-port-ext
      protocol: TCP
      port: 16687
      targetPort: 16686
  type: LoadBalancer
