apiVersion: v1
kind: ConfigMap
metadata:
  name: people-db-config
  namespace: nexus
data:
  POSTGRES_DB: "project_management_people"
  PGPORT: "5441"

---

apiVersion: v1
kind: Secret
metadata:
  name: people-db-secret
  namespace: nexus
type: Opaque
data:
  POSTGRES_USER: ZGV2ZWxvcGVy
  POSTGRES_PASSWORD: ZGV2MTIz
  
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: people-db-pvc
  namespace: nexus
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: people-db
  namespace: nexus
spec:
  selector:
    matchLabels:
      app: people-db
  template:
    metadata:
      labels:
        app: people-db
    spec:
      containers:
        - name: people-db
          image: postgres:latest
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: people-db-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: people-db-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: people-db-config
                  key: POSTGRES_DB
            - name: PGPORT
              valueFrom:
                configMapKeyRef:
                  name: people-db-config
                  key: PGPORT
          ports:
            - containerPort: 5441
          volumeMounts:
            - mountPath: /var/lib/postgresql
              name: people-db-storage
      volumes:
        - name: people-db-storage
          persistentVolumeClaim:
            claimName: people-db-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: people-db
  namespace: nexus
spec:
  selector:
    app: people-db
  ports:
    - protocol: TCP
      port: 5441
      targetPort: 5441
      
---

apiVersion: v1
kind: Service
metadata:
  name: people-api
  namespace: nexus
spec:
  ports:
    - port: 80
      name: http
    - port: 443
      name: https
  clusterIP: None
  selector:
    app: people-api

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: people-api
  namespace: nexus
spec:
  selector:
    matchLabels:
      app: people-api
  serviceName: people-api
  podManagementPolicy: Parallel
  replicas: 3
  updateStrategy:
    rollingUpdate:     
      partition: 0
    type: RollingUpdate
  
  template:
    metadata:
      labels:
        app: people-api
        
    spec:
      terminationGracePeriodSeconds: 10
      securityContext:
        fsGroup: 1000
      volumes:
        - name: devcerts
          secret:
            secretName: aspnetapp-cert
      containers:
        - name: people-api
          image: afroze9/nexus-people-api:latest
          ports:
            - containerPort: 80
            - containerPort: 443
          volumeMounts:
            - name: devcerts
              mountPath: /https/
          env:
            - name: ConsulKV__Url
              value: http://consul.nexus.svc.cluster.local:8500
            - name: ConsulKV__AddGlobalConfig
              value: "true"
            - name: ConsulKV__GlobalConfigKey
              value: "nexus-service/app-config"
            - name: ConsulKV__Key
              value: "people-api/app-config"
            - name: ConsulKV__Token
              valueFrom:
                secretKeyRef:
                  name: people-api-token
                  key: token
            - name: Consul__Host
              value: consul
            - name: GlobalConfiguration.BaseUrl
              value: http://localhost:5032
            - name: ASPNETCORE_URLS
              value: https://+:443;http://+:80
            - name: ASPNETCORE_Kestrel__Certificates__Default__Password
              value: dev123
            - name: ASPNETCORE_Kestrel__Certificates__Default__Path
              value: /https/aspnetapp.pfx