{
 "title": "Nexus Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Gen0 Heap Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "process_runtime_dotnet_gc_heap_size_bytes{generation=\"gen0\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GetAllCompanies Count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "company_api_getall_The_number_of_calls_to_GetAllCompanies_endpoint",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Times",
   "type": "histogram",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "http_client_duration_ms_bucket", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Gen1 Heap Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "process_runtime_dotnet_gc_heap_size_bytes{generation=\"gen1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gen2 Heap Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "process_runtime_dotnet_gc_heap_size_bytes{generation=\"gen2\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}