# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
      - master
  paths:
    include:
      - 'services/company-api/**'

pr:
  paths:
    include:
      - 'services/company-api/**'

pool:
  vmImage: 'windows-latest'

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  project: 'services/company-api/src/Nexus.Company.Api/Nexus.Company.Api.csproj'
  testProject: 'services/company-api/tests/Nexus.Company.Api.UnitTests/Nexus.Company.Api.UnitTests.csproj'
  testSettings: 'services/company-api/tests/Nexus.Company.Api.UnitTests/.runsettings'

steps:
- task: NuGetToolInstaller@1
  displayName: Install Nuget

- task: DotNetCoreCLI@2
  inputs:
    command: 'custom'
    custom: 'tool'
    arguments: 'install --global dotnet-reportgenerator-globaltool'

- task: SonarCloudPrepare@1
  displayName: 'Prepare SonarCloud Analysis'
  inputs:
    SonarCloud: 'SonarCloud'
    organization: 'nexus-framework'
    scannerMode: 'MSBuild'
    projectKey: 'nexus-framework.nexus.company'
    projectName: 'Nexus Company API'
    extraProperties: 'sonar.coverage.exclusions=**/*Migrations/*.cs'

- task: DotNetCoreCLI@2
  displayName: 'Restore Solution'
  inputs:
    command: 'restore'
    projects: $(project)
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  displayName: 'Build Company API'
  inputs:
    command: 'build'
    projects: $(project)
    arguments: '--configuration $(buildConfiguration) --no-restore'

- task: DotNetCoreCLI@2
  displayName: 'Run Unit Tests'
  inputs:
    command: test
    projects: $(testProject)
    arguments: '--collect "XPlat code coverage" --settings $(testSettings)'

- script: reportgenerator "-reports:*\*coverage.cobertura.xml" "-targetdir:codecoverage" "-reporttypes:SonarQube"
  displayName: Report Generator

- task: SonarCloudAnalyze@1
  displayName: 'Run SonarCloud Analysis'
  inputs:
    jdkversion: 'JAVA_HOME_17_X64'

- task: SonarCloudPublish@1
  displayName: 'Publish SonarCloud Results'
  inputs:
    pollingTimeoutSec: '300'
