trigger:
  branches:
    include:
      - master
  paths:
    include:
      - 'services/company-api/**'
      - 'Directory.Build.props'
      - 'Directory.Packages.props'
      - 'docker-compose.yml'
      - 'docker-compose-local.yml'
pr:
  paths:
    include:
      - 'services/company-api/**'

pool:
  vmImage: 'windows-latest'

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  project: 'services/company-api/src/Nexus.Company.Api/Nexus.Company.Api.csproj'
  unitTestProject: 'services/company-api/tests/Nexus.Company.Api.UnitTests/Nexus.Company.Api.UnitTests.csproj'
  componentTestProject: 'services/company-api/tests/Nexus.Company.Api.ComponentTests/Nexus.Company.Api.ComponentTests.csproj'
  runSettingsFile: '.runsettings'
  testSettings: 'services/company-api/tests/Nexus.Company.Api.UnitTests/.runsettings'
  packagesFile: 'services/company-api/src/Nexus.Company.Api/obj/project.assets.json'

steps:
- task: DotNetCoreCLI@2
  displayName: 'Restore Solution'
  inputs:
    command: 'restore'
    projects: $(project)
    feedsToUse: 'select'

- task: SonarCloudPrepare@1
  displayName: 'Prepare SonarCloud Analysis'
  inputs:
    SonarCloud: 'SonarCloud'
    organization: 'nexus-framework'
    scannerMode: 'MSBuild'
    projectKey: 'nexus-framework.nexus.company'
    projectName: 'Nexus Company API'
    extraProperties: |
      sonar.coverage.exclusions=**/*Migrations/*.cs

- task: DotNetCoreCLI@2
  displayName: 'Build Company API'
  inputs:
    command: 'build'
    projects: $(project)
    arguments: '--configuration $(buildConfiguration) --no-restore'

- task: DotNetCoreCLI@2
  displayName: 'Run Unit Tests'
  inputs:
    command: 'test'
    projects: '$(unitTestProject)'
    arguments: '-s $(testSettings)'

- task: DotNetCoreCLI@2
  displayName: 'Run Component Tests'
  inputs:
    command: 'test'
    projects: '$(componentTestProject)'
    arguments: '-s $(testSettings)'

- task: SonarCloudAnalyze@1
  displayName: 'Run SonarCloud Analysis'
  inputs:
    jdkversion: 'JAVA_HOME_17_X64'

- task: SonarCloudPublish@1
  displayName: 'Publish SonarCloud Results'
  inputs:
    pollingTimeoutSec: '300'

- task: SnykSecurityScan@1
  displayName: 'Snyk Security Scan'
  inputs:
    serviceConnectionEndpoint: 'Snyk'
    testType: 'app'
    severityThreshold: 'high'
    monitorWhen: 'always'
    failOnIssues: false
    projectName: 'Company API'
    organization: 'bd187a54-4038-4785-bd50-557c98a89868'
    additionalArguments: '--file=$(packagesFile)'